### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by jonalv** [cdk/depict#1]
I have tried: `mvn clean install`, but I get: 

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.708 s
[INFO] Finished at: 2017-08-08T09:37:32+02:00
[INFO] Final Memory: 10M/206M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cdkdepict: Could not resolve dependencies for project com.nextmovesoftware:cdkdepict:war:0.2: The following artifacts could not be resolved: org.openscience.cdk:cdk-depict:jar:2.0-SNAPSHOT, org.openscience.cdk:cdk-forcefield:jar:2.0-SNAPSHOT, uk.ac.ebi.beam:beam-core:jar:0.9.3: Could not find artifact org.openscience.cdk:cdk-depict:jar:2.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by johnmay** [comment]
Have add the SNAPSHOT repo to the pom and updated the version. Please let me know if this resolves it (don't really want to clear out by local repo).
