### ISSUE TITLE
Rotatable depiction possible?

### ISSUE THREAD

**Issue by schymane** [cdk/depict#10]
Are there any plans to add functionality to control rotation/orientation of depictions?
E.g. could I get this:
`C[N+]1=CC=C(C=C1)C1=CC=CC=C1`
http://simolecule.com/cdkdepict/depict/cot/svg?smi=C[N%2B]1=CC=C(C=C1)C1=CC=CC=C1&abbr=off&hdisp=bridgehead&showtitle=false&zoom=1.6&annotate=none
to lie horizontal instead of vertical, as just a simple example?
![image](https://user-images.githubusercontent.com/4070141/39879199-b3c3a162-5469-11e8-92c4-40cfa522f4cf.png)

This is really useful to help demonstrate structural similarity/differences, where it would be great to keep the orientation of the "base structure" consistent so that one can see/highlight the structural changes. I always ask for this as a reviewer, but can't do it myself yet automatically and I would love to be able to control this ... (or have I missed the option?). Sometimes a slight change in a substituent changes the entire orientation ..
Example (from ChemSketch, just to demonstrate):
![image](https://user-images.githubusercontent.com/4070141/39879124-8c746d4e-5469-11e8-86ef-d8b146b4fdda.png)

I'd add an "enhancement" label if I could ... it's just a suggestion but would be great.

**Comment by johnmay** [comment]
I have been thinking about this, but it would be very manual. The internal
version of CDK Depict does actually lay these flat -

**Comment by schymane** [comment]
Funny! It's highly sensitive to the groups sometimes too. Any way of controlling it would be highly appreciated, even if manual (one could save the settings then in a script to recreate). Right now I have to recreate all my images for publications/presentations in another viewer if I need the orientation consistent but I would really love to do everything with depict ... 
(for this case I just did screenshots and rotated everything 90° and patched over the N ... but a sharp eye will see it's not right).
How would you envisage adding the option? As a rotation angle?

**Comment by johnmay** [comment]
> Funny! It's highly sensitive to the groups sometimes too. 

Well the old algorithm rotates by 30 degree increments to find a) the maximum number of bonds "in snap" to +30/-30 degrees and b) then the best width. I've recently been tinkering such that the primary driving factor is the size of the bounding box. If it ends up vertical like this it will flip it 90 degrees. Also it doesn't like to rotate certain ring systems (e.g. steroids) that should have a set orientation.  I'm currently trying to figure out a way to balance this with the improved bounding box fitting.

> How would you envisage adding the option? As a rotation angle?

Yes

**Comment by miracle1111111** [comment]
Hello, there is a question recently that is very troublesome. Is it possible to set the font of the substituent separately, because the default substituent is italic, and the substituent I want to generate is a normal font. In addition, can the number in the upper right corner of the substituent be placed in the lower right corner? I don’t know where to set it. thank you very much

**Comment by johnmay** [comment]
Now possible
