### ISSUE TITLE
Duplicate Titles

### ISSUE THREAD

**Issue by schymane** [cdk/depict#13]
Aesthetics more than anything else: The more recent versions show a title by default (black), but then let you display the title as an extra as well (red) - which kind of looks strange on the main page. However just deactivating the title option means we don't get titles in the individual URLs...

![image](https://user-images.githubusercontent.com/4070141/42282562-3b495736-7fa7-11e8-927a-3bb7a6bcd7ce.png)

via direct [hyperlink ](http://www.simolecule.com/cdkdepict/depict/cow/svg?smi=OS(%3DO)(%3DO)CCC(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F%098%3A2%20FTSA&abbr=off&hdisp=bridgehead&showtitle=true&sma=FC(F)(%5BC%2CF%5D)%5BCH2%5D%5BCH2%5D%5B!%24(C(F)(F))%5D&zoom=1.6&annotate=none) it looks nice:
![image](https://user-images.githubusercontent.com/4070141/42282584-4f2ba6a0-7fa7-11e8-9252-4b76541e9e25.png)

**Comment by johnmay** [comment]
I'll rename the option - one title is in the image, one is the HTML. The button should be "Title in Image"
