### ISSUE TITLE
Depiction of C/N=C/C not as nice as C/C=C/C

### ISSUE THREAD

**Issue by baoilleach** [cdk/depict#15]
```C/N=C/C```is depicted as follows where the connection to the double bond from the carbon could be improved:
![png](https://user-images.githubusercontent.com/45337/60719113-90483f80-9f1e-11e9-80df-6cb340613284.png)
In contrast, ```C/C=C/C``` looks great:
![png](https://user-images.githubusercontent.com/45337/60719175-c1c10b00-9f1e-11e9-8bd5-5e5631d7aec4.png)

**Comment by johnmay** [comment]
Should be resolved by linked patch thanks.
