### ISSUE TITLE
Negative charge missing

### ISSUE THREAD

**Issue by baoilleach** [cdk/depict#19]
The SMILES string ```[N+](=O)([O-])[O-]``` is incorrectly depicted. There should be an ```O-``` in the depiction. (Not a fan of the coordinate bond, BTW - doesn't make sense to me in this context.)

**Comment by johnmay** [comment]
Fixed.

![](https://www.simolecule.com/cdkdepict/depict/bow/svg?smi=%5BO-%5D%5BN%2B%5D(%5BO-%5D)%3DO&abbr=on&hdisp=bridgehead&showtitle=false&zoom=1.6&annotate=none)

**Comment by johnmay** [comment]
BTW sometimes you move a hydrogen allowing the charge to be removed (with a H).

```C[N+]=CO>>C[NH+]C=O``
