### ISSUE TITLE
Inconsistent application of crossed bond

### ISSUE THREAD

**Issue by dan2097** [cdk/depict#2]
Please correct me if I'm wrong, but in:
`C[C@@]1(C)CC/C=C/(C)C1/C=C/C(C)=C/C=C/C(C)=C/C=C/C=C(C)/C=C/C=C(C)/C=C/C2C/(C)=C/CC[C@]2(C)C`
All double-bonds have their configurations defined, including the two that form part of six membered rings.
The last double bond in the SMILES however is depicted as being a crossed bond, despite both being defined and in the same environment (constrained by being in a 6-membered ring) as the first double bond in the SMILES.
[http://www.simolecule.com/cdkdepict/depict/bow/svg?smi=C[C@@]1(C)CC%2FC=C%2F(C)C1%2FC=C%2FC(C)=C%2FC=C%2FC(C)=C%2FC=C%2FC=C(C)%2FC=C%2FC=C(C)%2FC=C%2FC2C%2F(C)=C%2FCC[C@]2(C)C&w=80&h=50&abbr=on&hdisp=bridgehead&showtitle=true&zoom=5&annotate=none](url)
The molecule in question is epsilon,epsilon-carotene

**Comment by johnmay** [comment]
The cross bond is also used when it can't depict the specified configuration correctly. In this case you have a trans bond in six-membered ring.

Typically it will try and fit it in, or contort the rings as needed. However it will only do this in rings where double bond stereochemistry is deemed possible and thus the fall back puts in a cross bond indicate the configuration is not shown correctly. 

```C1C/C=C/C1.C1CC/C=C/C1.C1CCC/C=C/C1.C1CCCC/C=C/C1``` 
![image](https://user-images.githubusercontent.com/983232/32135535-b9a9f9be-bbf8-11e7-8213-82ad3b0fa538.png)

I can change this so for small rings it just ignores it but not sure whether that's for the best. It's useful when SMILES is possibly erroneous:

![image](https://user-images.githubusercontent.com/983232/32135561-1b05062c-bbf9-11e7-8852-6064f6d98b4c.png)
```
C[C@@]1(C)CC/C=C/(C)C1/C=C/C(C)=C/C=C/C(C)=C/C=C/C=C(C)/C=C/C=C(C)/C=C/C2C/(C)=C\CC[C@]2(C)C
```
or when cleaned off:
```
C[C@@]1(C)CC/C=C/(C)C1/C=C/C(C)=C/C=C/C(C)=C/C=C/C=C(C)/C=C/C=C(C)/C=C/C2C(C)=CCC[C@]2(C)C```

**Comment by dan2097** [comment]
Thanks, I hadn't actually noticed that one of the double-bonds was incorrectly trans. As most programs then ignore the configuration of <=6 membered rings it's surprisingly difficult to flag up the error, despite the fact that a correct depiction would give an extremely contorted structure.

Maybe just keep the current behaviour, I don't think anything short of a ChemDraw style red boxes would fully explain the issue, but those are not really appropriate for depictions.
