### ISSUE TITLE
symmetric mapping colour

### ISSUE THREAD

**Issue by asad** [cdk/depict#24]
The highlighted parts are not symmetrical in nature- is this expected?

Case1:
``` 
[O:1]=[C:2]([NH2:3])[CH2:4][CH2:5][CH2:6][CH3:7]>[NH4+:3]>[NH3:3]
```
Case:2
```
[NH3:3]>[NH4+:3]>[O:1]=[C:2]([NH2:3])[CH2:4][CH2:5][CH2:6][CH3:7]
````

Cheers,

-Asad

**Comment by johnmay** [comment]
Looking building up vs taking down, mainly was meant for synthetic chem so where did something come. Perfectly reasonable

As an aside off you have duplicate maps, maps are ignored in agents (ala Daylight):

```
[O:1]=[C:2]([NH2:3])[CH2:4][CH2:5][CH2:6][CH3:7]>[NH4+]>[NH3:3]
[O:1]=[C:2]([NH2:3])[CH2:4][CH2:5][CH2:6][CH3:7].[NH4+:8]>>[NH3:3]
[O:1]=[C:2]([NH2:3])[CH2:4][CH2:5][CH2:6][CH3:7].[NH4+:8]>>[NH3:8]
```



```
[O:1]=[C:2]([NH2:3])[CH2:4][CH2:5][CH2:6][CH3:7]>>[NH3:3].[O:1]=[CH:2][CH2:4][CH2:5][CH2:6][CH3:7]
[NH3:3].[O:1]=[CH:2][CH2:4][CH2:5][CH2:6][CH3:7]>>[O:1]=[C:2]([NH2:3])[CH2:4][CH2:5][CH2:6][CH3:7]
```

**Comment by johnmay** [comment]
![image](https://user-images.githubusercontent.com/983232/87979742-70a09c80-caca-11ea-8632-56cd782ce4a1.png)

**Comment by johnmay** [comment]
Sorry posted too early, it's mean't for "[matching](https://docs.chemaxon.com/display/AutoMapper_User%27s_Guide.html)" atom mapping style. Which would be:

![image](https://user-images.githubusercontent.com/983232/87979903-ad6c9380-caca-11ea-8c87-4b6bcc5e26c9.png)

[O]=[C]([NH2:3])[CH2][CH2][CH2][CH3]>[NH4+]>[NH3:3]

and

![image](https://user-images.githubusercontent.com/983232/87979913-b3627480-caca-11ea-8d35-e97cb2afba1e.png)


[NH3:3]>[NH4+]>[O]=[C]([NH2:3])[CH2][CH2][CH2][CH3]

However if a user gives a "complete" mapping then we could just ignore the un-mapped parts. P.s. Roger calls the style you provided "Completer"
