### ISSUE TITLE
Long Mol Text Fail

### ISSUE THREAD

**Issue by vinc3PO** [cdk/depict#27]
Molecules over 40 atoms can not be generated using the mol text in the parameter.

It might be due to a limitation in characters of the URL.  

For example:
CC(C)CC(C=C1)=CC=C1C2=CC3=CC=CC(C4=CC5=C(C=C(C6=CC=CC7=C6C=CC=C7)C=C5)C=C4)=C3C=C2
smiles works fine
mol text fails

the same with one carbon less
CCCC(C=C1)=CC=C1C2=CC3=CC=CC(C4=CC5=C(C=C(C6=CC=CC7=C6C=CC=C7)C=C5)C=C4)=C3C=C2
both work fine.

**Comment by johnmay** [comment]
I don't understand what you're asking, do you mean as MOLfile input?

**Comment by johnmay** [comment]
Yes likely URL limit, defacto is 2000 characters. I can't make it longer for img src="" but you may be able to POST the request. I thought this would work but it doesn't:

```
curl -XPOST -d "smi=@big.mol" "https://www.simolecule.com/cdkdepict/depict/bow/svg"
```

The upcoming depict version will actually allow you to paste the MOLfile/SDF in the text box directly. In your case if I generate the MOLfile with Marvin sketch I get ~4000k characters.

CDK has an option to generate a "truncated" MOLfile that omits the optional zero fields. This is actually the default on BIOVIA Sketch/Pipeline pilot. 

```

  Mrv1810 12052011002D          

 40 46  0  0  0  0            999 V2000
  -10.7171    3.7125    0.0000 C   0
  -10.0026    3.3000    0.0000 C   0
  -10.0026    2.4750    0.0000 C   0
   -9.2881    3.7125    0.0000 C   0
   -8.5737    3.3000    0.0000 C   0
   -7.8592    3.7125    0.0000 C   0
   -7.1447    3.3000    0.0000 C   0
   -8.5737    2.4750    0.0000 C   0
   -7.8592    2.0625    0.0000 C   0
   -7.1447    2.4750    0.0000 C   0
   -6.4302    2.0625    0.0000 C   0
   -5.7158    2.4750    0.0000 C   0
   -5.0013    2.0625    0.0000 C   0
   -4.2868    2.4750    0.0000 C   0
   -3.5724    2.0625    0.0000 C   0
   -3.5724    1.2375    0.0000 C   0
   -4.2868    0.8250    0.0000 C   0
   -4.2868   -0.0000    0.0000 C   0
   -5.0013   -0.4125    0.0000 C   0
   -5.0013   -1.2375    0.0000 C   0
   -4.2868   -1.6500    0.0000 C   0
   -4.2868   -2.4750    0.0000 C   0
   -5.0013   -2.8875    0.0000 C   0
   -5.0013   -3.7125    0.0000 C   0
   -5.7158   -4.1250    0.0000 C   0
   -5.7158   -4.9500    0.0000 C   0
   -5.0013   -5.3625    0.0000 C   0
   -4.2868   -4.9500    0.0000 C   0
   -4.2868   -4.1250    0.0000 C   0
   -3.5724   -3.7125    0.0000 C   0
   -2.8579   -4.1250    0.0000 C   0
   -2.8579   -4.9500    0.0000 C   0
   -3.5724   -5.3625    0.0000 C   0
   -5.7158   -2.4750    0.0000 C   0
   -5.7158   -1.6500    0.0000 C   0
   -3.5724   -1.2375    0.0000 C   0
   -3.5724   -0.4125    0.0000 C   0
   -5.0013    1.2375    0.0000 C   0
   -5.7158    0.8250    0.0000 C   0
   -6.4302    1.2375    0.0000 C   0
  1  2  1
  2  3  1
  2  4  1
  4  5  1
  5  6  1
  6  7  2
  5  8  2
  8  9  1
  9 10  2
  7 10  1
 10 11  1
 11 12  2
 12 13  1
 13 14  2
 14 15  1
 15 16  2
 16 17  1
 17 18  1
 18 19  2
 19 20  1
 20 21  2
 21 22  1
 22 23  2
 23 24  1
 24 25  2
 25 26  1
 26 27  2
 27 28  1
 28 29  2
 24 29  1
 29 30  1
 30 31  2
 31 32  1
 32 33  2
 28 33  1
 23 34  1
 34 35  2
 20 35  1
 21 36  1
 36 37  2
 18 37  1
 17 38  2
 13 38  1
 38 39  1
 39 40  2
 11 40  1
M  END
```

![image](https://user-images.githubusercontent.com/983232/101240849-c5475b80-36e9-11eb-923e-c17e6636af22.png)

**Comment by vinc3PO** [comment]
Hi, 
Exactly. 

My workaround  was to add an optional @requestBody  in the depict controler, check for emptiness of the smiles parameter and replace it with the text in the body.
Then send a post request with the MOLfile in the body.
I don't think there is a limitation in the size of the body.

**Comment by johnmay** [comment]
You should still be able to post the SMI parameter no? Are you running these on the main site, I got a CPU usage warning the last few days - settled down now. If you're just generating loads of images and saving them then it's more efficient to use call the CDK as a library.

**Comment by johnmay** [comment]
Send me a PR with the @requestbody and will try it out.

**Comment by vinc3PO** [comment]
It possibly was us. 
I was benchmarking and comparing molecules drawing tools. CDK, RDKit, openchemlib. 
But I have build it and it's now running on our server. 
That should be local now or am I missing something. 
I'll put my cloned version on my github sometime today.

**Comment by johnmay** [comment]
Yes that will be locally to you now. No issues I did just restart the server though at some points, I was more worried it was getting stuck on a given request. Up to you but for benchmark you can just use the actual API, the webapp does a lot more stuff on top, e.g. abbreviations, reaction alignment, hydrogen tuning, and is tuned to display 100 or so hits on a page.

**Comment by vinc3PO** [comment]
Truth is that we want to use only the REST part of the web app. But we are on time pressure to move forward quickly with our current project and at the moment complete build is fine. 

As I am unfamiliar (for the moment) with java, it easier for me to navigate around an existing project to get to what I need/want to achieve.

Later, I'll probably try to build a lightweight rest api build on the cdk library with only the necessary option.
