### ISSUE TITLE
numbering follows rule of ACDLab ChemSketch

### ISSUE THREAD

**Issue by biotech7** [cdk/depict#29]
Great work! it's very useful for numbering of molecules.
Recently I referred to CDK API mannual.  One of  CDKContants is **ACDLABS_LABEL**。So how
to use it in terms of numbering molecules. Is it be possibble to depict a labeled/numbering molucule follows as the numbering rule of  ACDLab ChemSketch? if so, how to configure this contant?
    the attachment labeled molecule(top right) drawed  in ChemSketch.
![111](https://user-images.githubusercontent.com/49674341/104675868-43534500-5721-11eb-943a-5675aeb76e9d.jpg)

**Comment by johnmay** [comment]
The depiction of labels on atoms/bonds shows anything placed in the "ANNOTATION_LABEL" property.

I don't have access to ChemSketch but I believe it stores these as some property in the molfile? If you are able to move these into the "atom value" field (confusingly called COMMENT) then you can depict it with the default options in the "DepictionGenerator" API class.

**Comment by biotech7** [comment]
Hi,  i am a little confused.  if a mol is labeled (by IUPAC rule) using ChemSketch, as for each atom，how can i find the corresponding atom which labeled by CDK's label rule in the same mol? Is there any labelling relationship/convertion which can be established between two rules？

**Comment by johnmay** [comment]
Sorry for any confusion but we don’t have an atom labelling algorithm. That is just a key (column heading) that can be used to store the property if you have it externally.

Atom numbers shown in the depiction are just based on the storage order

**Comment by biotech7** [comment]
solved my confusion. i'll try to find other way.
regards!
