### ISSUE TITLE
how to save a png file without background on server side?

### ISSUE THREAD

**Issue by biotech7** [cdk/depict#30]
Hi, 
by using the depict webapp client ,  a saved png file has no backgound (backgound is transparent，see attach.). but i cannot reproduce this operation on server side. That is to say, on the server side , exporting a png image will produce backgound. so how to save a png image without backgroud on server side? here are my codes:
        DepictionGenerator dg = new DepictionGenerator();
        IChemObjectBuilder bldr = SilentChemObjectBuilder.getInstance();
        SmilesParser smipar = new SmilesParser(bldr);
        IAtomContainer mol = smipar.parseSmiles("CN1C=NC2=C1C(=O)N(C(=O)N2C)C");
        dg.withSize(256, 256)
                .withMargin(10)
                .withAtomNumbers()
                .depict(mol)
                .writeTo(Depiction.PNG_FMT,"C:\\Users\\Alan\\Desktop\\cdk-mol.png");
![1](https://user-images.githubusercontent.com/49674341/104833113-383f1700-58d1-11eb-9ac9-c31795ea1a01.png)

**Comment by johnmay** [comment]
Give it a transparent background
```
.withBackgroundColor(new Color(0, 0, 0, 0));
```

**Comment by johnmay** [comment]
Please sign up to the mailing list, this is a question not an issue/bug

**Comment by johnmay** [comment]
Also not there is cdk/depict project which is a restful web app. That has simpler options like “colour or transparent” which would do what you need

**Comment by johnmay** [comment]
Ah just realised this issue is on that project, that piece of code you’re using is in the main project which confused me.

**Comment by biotech7** [comment]
@johnmay 
It works!  i omitted the fourth para in the _**.withBackgroundColor()**_。in my JAVA project, i need firstly render the png image on the server side. 
Regards!
