### ISSUE TITLE
Multi-step reaction SMILES?

### ISSUE THREAD

**Issue by schymane** [cdk/depict#33]
Not sure if this is feasible ... but wanted to ask ;-) 

The reaction SMILES functionality is awesome ... any chance we can deal with more steps?
The top three of these work ... the bottom one is invalid ... but would represent the flow of the top three. 
Top two: individual steps. Third: a "two step" reaction that works ... Fourth: nice to have but invalid.
If it's already possible and I just got the syntax wrong, I'm all ears!

```
C(=O)(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)O>[CF2 loss]>C(=O)(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)O PFHpA to PFHxA
C(=O)(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)O>[CF2 loss]>C(=O)(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)O PFHxA to PFPeA
C(=O)(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)O>[CF2 loss (x2)]>C(=O)(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)O PFHpA to PFPeA
C(=O)(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)O>[CF2 loss]>C(=O)(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)O>[CF2 loss]>C(=O)(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)O PFHpA to PFHxA to PFPeA

```
![image](https://user-images.githubusercontent.com/4070141/132961245-41ab57b7-9d33-481a-9ab6-b592bf6198eb.png)

**Comment by johnmay** [comment]
Would be nice but a bespoke format/extension which I'm not really a fan off. Fundamentally CDK data structures make this tricky (more structures needed) and it would be always be limited by the URL length....

Maybe one day but beyond something quick and dirty fix it's challenging

**Comment by schymane** [comment]
Thanks! Hmm yes I suspected it may involve something beyond a quick fix ...

**Comment by johnmay** [comment]
Check it out :-) 

![image](https://github.com/cdk/depict/assets/983232/8813a608-8aa0-4463-9faf-90f7f9a9d8e7)

**Comment by schymane** [comment]
This looks awesome! It hasn't filtered through yet to CDK Depict tho, right? 
(I still get invalid SMILES if I try either my example above or your examples in https://github.com/cdk/cdk/pull/986)

We're using CDK Depict to curate Emma P's [ShinyTPs](https://gitlab.lcsb.uni.lu/eci/shinytps) work and multistep reactions are in our future perspectives for sure, this is very cool to see!

**Comment by johnmay** [comment]
No I submitted the PR yesterday, which examples don't work. 

This examples works fine on the branch:

```
C(=O)(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)O>[CF2 loss]>C(=O)(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)O>[CF2 loss]>C(=O)(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)O PFHpA to PFHxA to PFPeA
```
![tmp_0](https://github.com/cdk/depict/assets/983232/a50b61f7-6382-49e7-b672-2cb43f5ab15f)

The "CF2 Loss" is probably better as a title/condition. Space is not normally allowed in atom symbols :-).

```java
for (IReaction reaction : reactionSet.reactions()) {
    reaction.setProperty(CDKConstants.REACTION_CONDITIONS, "CF2 Loss");
}
```

![tmp_0](https://github.com/cdk/depict/assets/983232/78704845-1b86-44d9-a045-2ca91bdcc4da)

**Comment by johnmay** [comment]
Ignore the I-1, I-2, I-3 I was just playing around with compound naming.

**Comment by schymane** [comment]
I just tried it directly on the [website](https://www.simolecule.com/cdkdepict/depict.html) copy pasting the SMILES from your issues cos I was curious... 

![image](https://github.com/cdk/depict/assets/4070141/d73f5356-a2fe-4e4a-8cb9-58a52a6e3f55)

**Comment by johnmay** [comment]
Yes as I said, it's not merged into CDK yet so won't be on the production website for sometime. Was just letting you know this was in the works.

**Comment by schymane** [comment]
Was very happy to see that it's in the works! ;-)
