### ISSUE TITLE
Option to depict Molfile-provided coordinates

### ISSUE THREAD

**Issue by baoilleach** [cdk/depict#34]
Hi John. Would it be possible to add an option (or make it the default) to use the coordinates as provided if a Molfile is passed in? As far as I can tell, the sdg is always called, but preserving the coords is pretty much the use-case for sending in a Molfile - the med chemists within a project standardise on certain orientations and preserving this helps them.

**Comment by johnmay** [comment]
Sure makes sense - I'll take a look. Should also be possible go via CXSMILES which would be a short URL and embeddable in a img href. Leave it with me.

**Comment by johnmay** [comment]
Fixed via 8bf7fe1

**Comment by johnmay** [comment]
I should add the ability to set the wedges when coming in via CXSMILES but that isn't a public function.

**Comment by baoilleach** [comment]
Thanks John.
