### ISSUE TITLE
Isotope support?

### ISSUE THREAD

**Issue by schymane** [cdk/depict#4]
Benzene-D6: [2H]C1=C([2H])C([2H])=C([2H])C([2H])=C1[2H] 
From https://comptox.epa.gov/dashboard/dsstoxdb/results?search=DTXSID7037769
fails: 
http://simolecule.com/cdkdepict/depict/bow/svg?smi=[2H]C1=C([2H])C([2H])=C([2H])C([2H])=C1[2H]&abbr=off&hdisp=bridgehead&showtitle=true&zoom=1.3&annotate=none 
Workaround with "D" displays:
http://simolecule.com/cdkdepict/depict/bow/svg?smi=[D]C1=C([D])C([D])=C([D])C([D])=C1[D]&abbr=off&hdisp=bridgehead&showtitle=true&zoom=1.3&annotate=none 
But I haven't found a nice display workaround for 13C yet - any suggestions?
C1=CC=[13CH]C=C1 
Source: https://comptox.epa.gov/dashboard/dsstoxdb/results?search=DTXSID60480506 
[13CH]1=[13CH][13CH]=[13CH][13CH]=[13CH]1
Source: https://pubchem.ncbi.nlm.nih.gov/compound/11309472#section=Isomeric-SMILES

**Comment by rajarshi** [comment]
I think the `[D]` vs `[2H]` is a CDK issue - you should probably check on the cdk-user list

**Comment by schymane** [comment]
The Ds display because they are treated as plain text (which is useful). I guess other isotopes aren't supported yet, which is a CDK issue indeed. I can't subscribe to the user list from my phone ;-( so will have to post that another time
-------------------------------------------




On Sun, Oct 22, 2017 at 8:59 PM +0200, "Rajarshi Guha" <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the [D] vs [2H] is a CDK issue - you should probably check on the cdk-user list

**Comment by schymane** [comment]
I am not sure this is a CDK issue in general - this for instance works in R:
m <- parse.smiles("c1cc[13cH]cc1")[[1]]
dep <- get.depictor(width=200, height=200)
img <- view.image.2d(m, dep)
plot(1:10, 1:10, pch=19)
rasterImage(img, 2,2,8,8)

![image](https://user-images.githubusercontent.com/4070141/31938191-2a2ebd72-b8b7-11e7-8009-edb13c840ca3.png)

But in depict a broken link:
http://www.simolecule.com/cdkdepict/depict/bow/svg?smi=c1cc[13cH]cc1&abbr=on&hdisp=bridgehead&showtitle=false&zoom=1.3&annotate=none 

SMILES from here:
http://www.chemspider.com/Chemical-Structure.16787922.html 

This also works:
http://www.chemspider.com/Chemical-Structure.109717.html 
m <- parse.smiles("[2H]c1ccccc1")[[1]]
img <- view.image.2d(m, dep)
rasterImage(img, 2,2,8,8)

![image](https://user-images.githubusercontent.com/4070141/31938310-88f5825a-b8b7-11e7-97d7-071194dc9a98.png)

but again not in depict:
http://www.simolecule.com/cdkdepict/depict/bow/svg?smi=[2H]c1ccccc1&abbr=on&hdisp=bridgehead&showtitle=false&zoom=1.3&annotate=none 

Am I missing an option somewhere?

**Comment by rajarshi** [comment]
Hmm, not sure. If it's an issue in the depict app, then contacting @johnmay is a good idea

**Comment by johnmay** [comment]
Sorry this was a recent bug I introduced when fixing isotope handling in the CDK.... might actually already be fixed but not redeployed for a while.

**Comment by johnmay** [comment]
On latest build I get:

![image](https://user-images.githubusercontent.com/983232/32137046-acfba38a-bc10-11e7-8b96-96634a6aac55.png)
![image](https://user-images.githubusercontent.com/983232/32137047-b0aa79ac-bc10-11e7-8191-5a65db34f396.png)
![image](https://user-images.githubusercontent.com/983232/32137049-b46aef0e-bc10-11e7-9620-e195f722ed0d.png)
Correct?

**Comment by johnmay** [comment]
Should be fixed now on public server, please confirm and I'll close the issue

**Comment by schymane** [comment]
Looks awesome, I tried some random non-standard isotope forms of atrazine (14C, 15N, D) from the Dashboard and all looked good. Thanks!
