### ISSUE TITLE
Transparent background bug in labeled group display

### ISSUE THREAD

**Issue by schymane** [cdk/depict#5]
The images with transparent background seem to have a minor bug in the display of labeled groups, e.g.
Colour on transparent:
http://www.simolecule.com/cdkdepict/depict/cot/svg?smi=CC(C)[C@H](N*)C(*)=O%20%7C%24%3B%3B%3B%3B%3B_AP1%3B%3B_AP2%3B%24%7C%20valine%20monomer&abbr=off&hdisp=bridgehead&showtitle=false&sma=a1aaaaa1%20&zoom=1.9&annotate=none

![image](https://user-images.githubusercontent.com/4070141/33209936-7becc5a4-d118-11e7-99ac-e7d5017dbb96.png)

Black on Transparent:
![image](https://user-images.githubusercontent.com/4070141/33209968-94deb888-d118-11e7-9d3d-17dbdf35846e.png)

But on black or white background you see the 1 and 2, not just black dots.
![image](https://user-images.githubusercontent.com/4070141/33209995-ae2012d8-d118-11e7-9e46-77743a71aa5d.png)

![image](https://user-images.githubusercontent.com/4070141/33210008-ba62ec0a-d118-11e7-9119-56cb150fcd66.png)

**Comment by johnmay** [comment]
https://github.com/cdk/cdk/pull/386
