### ISSUE TITLE
thoughts about input of .sdf (version 3000) / extended stereochemistry

### ISSUE THREAD

**Issue by nbehrnd** [cdk/depict#53]
This spurs off of a discussion [here](https://github.com/cdk/depict/issues/52) and a contribution by @adafede about atom numbering.  At present, the program allows input as SMILES, or copy-paste of .sdf.  If present and requested, it can can assign and label stereochemistry, too.

Venturing out a couple of variations about and around tartaric acid sketched in [DataWarrior](https://openmolecules.org/datawarrior/index.html) (repository [on GitHub](https://github.com/thsa/datawarrior)), I noticed CDKdepict does not process DataWarrior's structures exported in the more recent V3000 dialect of .sdf.  Extending the more senior format, this allows to store and process extended stereochemistry as in `&` and `or` for a stereogenic centre:

![entry_05](https://user-images.githubusercontent.com/19709084/197986727-97e5980f-096c-4f24-89c5-1a85949f2e92.png)

Do you think the additional file format and its extended functionality would be worth the effort to be implemented into future versions of CDKDepict?

[2022-10-26_stereochemistry_variations.zip](https://github.com/cdk/depict/files/9868014/2022-10-26_stereochemistry_variations.zip)

**Comment by johnmay** [comment]
Depict is primarily for SMILES input and this is possible with the CXSMILES extensions. Try these out.

```
OC(=O)[C@H](O)[C@H](O)C(=O)O |&1:3|
OC(=O)[C@H](O)[C@H](O)C(=O)O |o1:3|
OC(=O)[C@H](O)[C@H](O)C(=O)O |&1:3,5|
OC(=O)[C@H](O)[C@H](O)C(=O)O |o1:3,5|
```

I really don't like allow MOLfile and I think the key issue here is we only expect V2000, so in practise it's a simple fix.

**Comment by johnmay** [comment]
Fixed, will need to shift reload the webpage as the JS needed updating.

Note in SMILES/depict "ABS" is default and not displayed (same as chiral flag=1), if you set chiral_flag=0 will see the different. 

Anyways on your examples it's really on the last two where you see it.

![Screenshot 2022-10-26 at 13 05 04](https://user-images.githubusercontent.com/983232/198021632-7f736069-7171-49fc-9cd9-b5fbaf712b05.png)
