### ISSUE TITLE
mark missing stereo

### ISSUE THREAD

**Issue by Adafede** [cdk/depict#54]
Sometimes, it is hard to spot missing stereo on structures, having a way to mark them would be helpful to many of us, I guess!

Please tell me if further development is needed! 😊

**Comment by johnmay** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/983232/198021219-d9cd2010-3940-4f41-aac6-08e22c7f3967.png)

**Comment by johnmay** [comment]
I could also add a wavy bond perhaps.
