### ISSUE TITLE
feature request: generating multiple molecue structures within one image

### ISSUE THREAD

**Issue by biotech7** [cdk/depict#75]
Hi,John, 
based on multiple extended smiles like: "CN1C=NC2=C1C(=O)N(C(=O)N2C)C caffeine.CN1C=NC2=C1C(=O)N(C(=O)N2C)C caffeine.CN1C=NC2=C1C(=O)N(C(=O)N2C)C caffeine" to generate multiple structures in one image , which contain title informations look like followiing. is it applicabale?
<img width="605" alt="depict" src="https://github.com/cdk/depict/assets/49674341/c36cfdad-f9f0-4fd6-b33d-6cc1ea63094f">

**Comment by johnmay** [comment]
This is possible using the CDK depict API but I would prefer to not add this to the front end since you can do it with more flexibility with HTML/JS/CSS.

Here is it using the API BTW

```java
IChemObjectBuilder builder = SilentChemObjectBuilder.getInstance();
SmilesParser smipar = new SmilesParser(builder);
List<IAtomContainer> molecules = new ArrayList<>();
molecules.add(smipar.parseSmiles("CN1C=NC2=C1C(=O)N(C(=O)N2C)C caffeine"));
molecules.add(smipar.parseSmiles("CN1C=NC2=C1C(=O)N(C(=O)N2C)C caffeine"));
molecules.add(smipar.parseSmiles("CN1C=NC2=C1C(=O)N(C(=O)N2C)C caffeine"));
new DepictionGenerator().withMolTitle()
                        .depict(molecules, 1, 3)
                        .writeTo("/tmp/tmp.svg");
```

 
![tmp](https://github.com/cdk/depict/assets/983232/2976fc3c-a45c-405e-b5fc-0a55a0614bb8)
