### ISSUE TITLE
The on-line version fails when highlighting is requested on no-kekulisable smiles

### ISSUE THREAD

**Issue by sauliusg** [cdk/depict#9]
The on-line version at http://www.simolecule.com/cdkdepict/depict.html displays nicely the non-kekulisable SMILES like 'n1cccc1', but fails to produce an image when "Highlight" is requested:
![screenshot from 2018-02-27 17-48-36](https://user-images.githubusercontent.com/10668420/36738699-d810054e-1be6-11e8-8b27-45bc024c96f1.png)
Error (exception) message, available at the "broken image" link, was: 'org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException: Bond order was not set.'.
The issue is not reproducible locally, as the downloaded or checked-out and compiled cdkdepict 0.{1,2,3} releases do not parse the 'n1cccc1' on the local machines (see issue #8 ).

**Comment by johnmay** [comment]
Yes the SMILES is not valid and the structure is in an inconsistent state so things go bananas internally. I've recently relaxed it so you can at least display them but I make no guarentees anything else will work.
